<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myapp" nsURI="http://test/1.0" nsPrefix="myapp">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SingletonComponent"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="2 composants ne peuvent pas avoir le mm nom"/>
      </eAnnotations>
      <details key="SingletonComponent" value="self.component->forAll(c1, c2 | c1 &lt;> c2 implies c1.componentName&lt;>c2.componentName)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SingletonService"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="2 services ne peuvent pas avoir le mm nom"/>
      </eAnnotations>
      <details key="SingletonService" value="self.service->forAll(i1, i2 | i1 &lt;> i2 implies i1.ServiceName&lt;>i2.ServiceName)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        upperBound="-1" eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredService" eSuperTypes="#//Service">
    <eOperations name="Get" upperBound="-1" eType="#//ProvidedService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedservice" upperBound="-1"
        eType="#//ProvidedService" eOpposite="#//ProvidedService/requiredservice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedService" eSuperTypes="#//Service">
    <eOperations name="Get" upperBound="-1" eType="#//RequiredService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredservice" upperBound="-1"
        eType="#//RequiredService" eOpposite="#//RequiredService/providedservice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
